export const SAVE_TOKEN = 'SAVE_TOKEN';
export const SAVE_REQUEST_INIT_INFO = 'SAVE_REQUEST_INFO';
export const SAVE_APP_ID = 'SAVE_APP_ID';
export const SAVE_REQUEST_LOGIN_INFO = 'SAVE_REQUEST_LOGIN_INFO';
