CREATE TABLE TBL_MMBR
(
    MMBR_ID     BIGINT AUTO_INCREMENT,
    MMBR_NCK_NM VARCHAR(50)  NULL,
    MMBR_HNDC   TINYINT      NULL,
    RGST_DT     DATETIME     NOT NULL,
    MDFY_DT     DATETIME     NULL,
    KKO_LGN_ID  BIGINT       NOT NULL,
    LGN_TKN     VARCHAR(255) NOT NULL,
    PRIMARY KEY (MMBR_ID)
);

CREATE TABLE TBL_CNTS
(
    CNTS_ID       BIGINT AUTO_INCREMENT,
    CNTS_NM       VARCHAR(100) NOT NULL,
    CNTS_DSCR     TEXT         NULL,
    STRT_DATE     DATE         NULL     DEFAULT NULL,
    STRT_TIME     TIME         NULL,
    END_DATE      DATE         NOT NULL DEFAULT NULL,
    END_TIME      TIME         NULL,
    PRGR_STT      CHAR(1)      NOT NULL,
    MAX_PRTC_PRSN INT          NULL,
    RGST_MNGR_ID  BIGINT       NOT NULL,
    RGST_DT       DATETIME     NOT NULL,
    MDFY_MNGR_ID  BIGINT       NULL,
    MDFY_DT       DATETIME     NULL,
    PRIMARY KEY (CNTS_ID)
);

CREATE TABLE TBL_PLYR
(
    PLYR_ID   BIGINT AUTO_INCREMENT,
    CNTS_ID   BIGINT  NOT NULL,
    MMBR_ID   BIGINT  NOT NULL,
    PLYR_NO   INT     NULL,
    PRTC_HNDC TINYINT NULL,
    PLYR_RNKN INT     NULL,
    PLYR_SCR  INT     NULL,
    PRIMARY KEY (PLYR_ID)
);

CREATE TABLE TBL_GAME_RSLT_INPT
(
    GAME_RSLT_INPT_ID BIGINT AUTO_INCREMENT,
    PLYR_ID           BIGINT   NOT NULL,
    OPNN_PLYR_ID      BIGINT   NOT NULL,
    FRST_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    SCND_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    THRD_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    INPT_DT           DATETIME NULL,
    PRIMARY KEY (GAME_RSLT_INPT_ID)
);

CREATE TABLE TBL_GAME_RSLT_CNFR
(
    GAME_RSLT_CNFR_ID BIGINT AUTO_INCREMENT,
    PLYR_ID           BIGINT   NOT NULL,
    PLYR_INPT_ID      BIGINT   NOT NULL,
    OPNN_PLYR_ID      BIGINT   NOT NULL,
    OPNN_PLYR_INPT_ID BIGINT   NOT NULL,
    FRST_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    SCND_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    THRD_RSLT         CHAR(1)  NOT NULL DEFAULT '0',
    CNFR_MNGR_ID      BIGINT   NOT NULL,
    CNFR_DT           DATETIME NOT NULL,
    PRIMARY KEY (GAME_RSLT_CNFR_ID)
);

CREATE TABLE TBL_MNGR
(
    MNGR_ID     BIGINT AUTO_INCREMENT,
    LGN_ID      VARCHAR(100) NOT NULL,
    LGN_BOX     VARCHAR(255) NOT NULL,
    LAST_LGN_DT DATETIME     NULL,
    PRIMARY KEY (MNGR_ID)
);

CREATE TABLE TBL_NTC
(
    NTC_ID       BIGINT AUTO_INCREMENT,
    NTC_TTL      VARCHAR(255) NOT NULL,
    NTC_CNTN     TEXT         NOT NULL,
    TRGT_CNTS_ID BIGINT       NULL,
    CAN_SKIP     CHAR(1)      NOT NULL DEFAULT 'N',
    RGST_MNGR_ID BIGINT       NOT NULL,
    RGST_DT      DATETIME     NOT NULL,
    MDFY_MNGR_ID BIGINT       NULL,
    MDFY_DT      DATETIME     NULL,
    PRIMARY KEY (NTC_ID)
);

CREATE TABLE TBL_KKO_LGN
(
    LGN_ID            BIGINT,
    LST_CNCT_DT       DATETIME     NOT NULL,
    NCK_NM            VARCHAR(255) NULL,
    PRFL_IMG_URL      VARCHAR(255) NULL,
    PRFL_THMB_IMG_URL VARCHAR(255) NULL,
    PRIMARY KEY (LGN_ID)
);

ALTER TABLE TBL_MMBR
    ADD FOREIGN KEY (KKO_LGN_ID) REFERENCES TBL_KKO_LGN (LGN_ID);

ALTER TABLE TBL_PLYR
    ADD FOREIGN KEY (CNTS_ID) REFERENCES TBL_CNTS (CNTS_ID);

ALTER TABLE TBL_PLYR
    ADD FOREIGN KEY (MMBR_ID) REFERENCES TBL_MMBR (MMBR_ID);

ALTER TABLE TBL_GAME_RSLT_CNFR
    ADD FOREIGN KEY (PLYR_ID) REFERENCES TBL_PLYR (PLYR_ID);

ALTER TABLE TBL_GAME_RSLT_CNFR
    ADD FOREIGN KEY (PLYR_INPT_ID) REFERENCES TBL_GAME_RSLT_INPT (GAME_RSLT_INPT_ID);

ALTER TABLE TBL_GAME_RSLT_CNFR
    ADD FOREIGN KEY (OPNN_PLYR_INPT_ID) REFERENCES TBL_GAME_RSLT_INPT (GAME_RSLT_INPT_ID);

ALTER TABLE TBL_GAME_RSLT_CNFR
    ADD FOREIGN KEY (OPNN_PLYR_ID) REFERENCES TBL_PLYR (PLYR_ID);

ALTER TABLE TBL_GAME_RSLT_CNFR
    ADD FOREIGN KEY (CNFR_MNGR_ID) REFERENCES TBL_MNGR (MNGR_ID);

ALTER TABLE TBL_NTC
    ADD FOREIGN KEY (TRGT_CNTS_ID) REFERENCES TBL_CNTS (CNTS_ID);

ALTER TABLE TBL_NTC
    ADD FOREIGN KEY (RGST_MNGR_ID) REFERENCES TBL_MNGR (MNGR_ID);

ALTER TABLE TBL_NTC
    ADD FOREIGN KEY (MDFY_MNGR_ID) REFERENCES TBL_MNGR (MNGR_ID);

ALTER TABLE TBL_CNTS
    ADD FOREIGN KEY (RGST_MNGR_ID) REFERENCES TBL_MNGR (MNGR_ID);

ALTER TABLE TBL_CNTS
    ADD FOREIGN KEY (MDFY_MNGR_ID) REFERENCES TBL_MNGR (MNGR_ID);
