name: Test Back-End (Java) with SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 소나큐브를 실행하려면 JDK 11 버전이 필요하다.
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: back-end
      - name: Check gradle version
        run: ./gradlew -v
        working-directory: back-end
      - name: Run build
        run: ./gradlew --console verbose build
        working-directory: back-end
      - name: Run test
        run: ./gradlew --console verbose test
        working-directory: back-end
      - name: Make jacoco report
        run: ./gradlew --console verbose jacocoTestReport
        working-directory: back-end
      - name: Report SonarClude
        run: ./gradlew --stacktrace --console verbose --info sonarqube
        working-directory: back-end
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      이력을 남긴다. 그래들 프로젝트는 플러그인으로 검사 하라고 한다 ㅠㅠ
#      Gradle project detected. You should use the SonarQube plugin for Gradle during build rather than using this GitHub Action.
#      - name: Analyze with SonarCloud
#        uses: sonarsource/sonarcloud-github-action@master
#        with:
#          projectBaseDir: back-end
#          args: >
#            -Dsonar.organization=antop-dev-github
#            -Dsonar.projectKey=antop-dev_billiards-love:back-end
#            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport.xml
#            -Dsonar.verbose=true
#            -Dsonar.sourceEncoding=UTF-8
#            -Dsonar.java.source=1.8
#            -Dsonar.java.target=1.8
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
